# Site settings
name: elephant在写回忆录
email: chaojuanxiang@126.com
author: elephant
url: http://elephantsuperjuan.github.io/elephant/
resume_site: http://elephantsuperjuan.github.io/elephant/2015/08/22/resume/
github: https://github.com/elephantsuperjuan
baseurl: "/elephant"
description: Actually, less is more!
meta_description: 项超娟;个人博客;学而不思则罔;思而不学则殆;交流思考才能进步
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: elephantsuperjuan
highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : luoyan35714
    disqus :
        short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light